"""Agentic shared utilities."""
__version__ = "0.1.0"

from .nats_subjects import (
    CONTROL_START_SUBJECT_TEMPLATE,
    CONTROL_CLOSE_SUBJECT_TEMPLATE,
    CONTROL_RESUME_SUBJECT_TEMPLATE,
    CONTROL_WORKER_READY_SUBJECT_TEMPLATE,
    CONTROL_WILDCARD_SUBJECT,
    CHAT_USER_EVENTS_SUBJECT_TEMPLATE,
    CHAT_WORKER_EVENTS_SUBJECT_TEMPLATE,
    CHAT_WILDCARD_SUBJECT,
    CHAT_ERRORS_SUBJECT,
    EVENT_STATE_SUBJECT_TEMPLATE,
    EVENT_STATE_WILDCARD_SUBJECT_TEMPLATE,
    EVENT_WILDCARD_SUBJECT,
    STREAM_AGENT_CHAT,
    STREAM_AGENT_CONTROL,
    STREAM_AGENT_EVENTS,
    STREAM_AGENT_ERRORS,
    format_control_start,
    format_control_close,
    format_control_resume,
    format_control_worker_ready,
    format_chat_user_events,
    format_chat_worker_events,
    format_event_state,
    format_event_state_wildcard,
)
from .nats_streams import get_crewai_stream_configs

__all__ = [
    "CONTROL_START_SUBJECT_TEMPLATE",
    "CONTROL_CLOSE_SUBJECT_TEMPLATE",
    "CONTROL_RESUME_SUBJECT_TEMPLATE",
    "CONTROL_WORKER_READY_SUBJECT_TEMPLATE",
    "CONTROL_WILDCARD_SUBJECT",
    "CHAT_USER_EVENTS_SUBJECT_TEMPLATE",
    "CHAT_WORKER_EVENTS_SUBJECT_TEMPLATE",
    "CHAT_WILDCARD_SUBJECT",
    "CHAT_ERRORS_SUBJECT",
    "EVENT_STATE_SUBJECT_TEMPLATE",
    "EVENT_STATE_WILDCARD_SUBJECT_TEMPLATE",
    "EVENT_WILDCARD_SUBJECT",
    "STREAM_AGENT_CHAT",
    "STREAM_AGENT_CONTROL",
    "STREAM_AGENT_EVENTS",
    "STREAM_AGENT_ERRORS",
    "format_control_start",
    "format_control_close",
    "format_control_resume",
    "format_control_worker_ready",
    "format_chat_user_events",
    "format_chat_worker_events",
    "format_event_state",
    "format_event_state_wildcard",
    "get_crewai_stream_configs",
]
